kind: ConfigMap
apiVersion: v1
metadata:
    name: {{ include "configMap.name" $ }}
    namespace: {{ .Release.Namespace }}
data:
    host: {{ required "A pfsense host is required" .Values.pfsense.host }}
    scheme: {{.Values.pfsense.scheme }}