kind: Secret
apiVersion: v1
metadata:
  name: {{ include "configMap.name" $ }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  user: {{ .Values.pfsense.user | b64enc | quote }}
  password: {{ .Values.pfsense.password | b64enc | quote }}
